# Generated by Django 2.2.7 on 2021-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_address', models.CharField(max_length=128)),
                ('emp_salary', models.IntegerField()),
                ('emp_position', models.CharField(choices=[('team_lead', 'Team Lead'), ('project_manager', 'Project Manager'), ('software_engineer', 'Software Engineer'), ('tester', 'Tester')], default='software_engineer', max_length=10)),
            ],
        ),
    ]
