# Generated by Django 2.2.7 on 2021-03-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_position',
            field=models.CharField(choices=[('team_lead', 'Team Lead'), ('project_manager', 'Project Manager'), ('software_engineer', 'Software Engineer'), ('tester', 'Tester')], default='software_engineer', max_length=20),
        ),
    ]
